// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkvzmgydluxpzcjyfxue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdnptZ3lkbHV4cHpjanlmeHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODA3ODgsImV4cCI6MjA2NzE1Njc4OH0.tq2CCQyR7k3Fm9deQkwU5jvejWMlhPXE4qteSo7CpZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});